# Generated by Django 6.0.4 on 2026-04-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='fetured_image',
            new_name='featured_image',
        ),
    ]
