# Generated by Django 6.0.4 on 2026-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_about_created_at_about_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'Social Links'},
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='media_link',
            field=models.URLField(),
        ),
    ]
